### ISSUE TITLE
make install suggestion

### ISSUE THREAD

**Issue by stefets** [danieloneill/alsalist#1]
Hi!

It will be very usefull for me but what do you think about a make install ?

The `make install` will copy the alsalist binary in `/usr/local/bin` for example

What do you think ?

**Comment by danieloneill** [comment]
I think that's a reasonable request, I'll add a couple more lines to the 2-line Makefile 🤣

**Comment by danieloneill** [comment]
Updated in https://github.com/danieloneill/alsalist/commit/b37e2fc92da6d00aa82de9cfa5422341ac2ffa4c

**Comment by stefets** [comment]
Thanks! It' very useful for me ! I do seven replace in my script with the program. I was going crazy to adjust the alsa ports manually.
